### ISSUE TITLE
Problem instrumenting infrastructure nodes

### ISSUE THREAD

**Issue by pahofmann** [Dynatrace/dynatrace-oneagent-operator#128] opened 2019-08-29 13:17 UTC
We want to instrument the infrastructure nodes of our customers cluster to get insides into the OpenShift Router pods.  

We tagged them with the relevant node selectors (label apm=test in this case), which works fine for the worker nodes: 

```
  nodeSelector: 
    apm: test 
  # https://kubernetes.io/docs/concepts/configuration/taint-and-toleration/ (optional) 
  tolerations: 
  - effect: NoSchedule 
    key: node-role.kubernetes.io/master 
    operator: Exists
```

The node has the correct label and is not a master node:
```
$ oc describe node OurInfrastructureNode
Name:          OurInfrastructureNode
Roles:              infra 
Labels:             apm=test 
                    beta.kubernetes.io/arch=amd64 
                    beta.kubernetes.io/os=linux 
                    infra=true 
                    kubernetes.io/hostname=OurInfrastructureNode
                    logging-infra-fluentd=true 
                    node-role.kubernetes.io/infra=true 
                    region=infra 
                    router=yes 
                    zone=sztest 
Annotations: node.openshift.io/md5sum=efb9495187b03dc6x4bd217742d52cf1 
                    volumes.kubernetes.io/controller-managed-attach-detach=true 
```
Still no OneAgent is deployed to those nodes, there is no information about an deployment attempt in the logs.  
Are the infrastructure nodes excluded by other means?

**Comment by lrgar** [comment] 2019-08-29 13:29
Hi, thank you for your message.

Aside from the node selector, Kubernetes rejects to run pods (our OneAgent pod for instance) if there is a "taint" on the node, unless there is a "toleration" on the pod. Could you please list the taints for your node? They also appear with "oc describe node".

Alternatively, there could be no resources to deploy the OneAgent pod into that node. Can you confirm with `oc get ds -n dynatrace`?

**Comment by pahofmann** [comment] 2019-08-29 13:48
The OneAgent custom resource is there and works fine for deploying to the worker nodes.
The infrastructure node has no taints:
```
.....
Roles: infra
Labels: apm=test
beta.kubernetes.io/arch=amd64
beta.kubernetes.io/os=linux
infra=true
kubernetes.io/hostname=adle052p.de.top.com
logging-infra-fluentd=true
node-role.kubernetes.io/infra=true
region=infra
router=yes
zone=sztest
Annotations: node.openshift.io/md5sum=efb9495187b03dc6d4bd217742d52cf1
volumes.kubernetes.io/controller-managed-attach-detach=true
CreationTimestamp: Tue, 04 Jun 2019 14:08:30 +0200
Taints: <none>
```

**Comment by lrgar** [comment] 2019-08-29 14:41
Our Operator creates a DaemonSet, which is in charge of deploying an OneAgent pod into every node of your cluster, as configured by the node selector.

If the node selector and tolerations are configured correctly, and it looks like it from above, then you should have the OneAgent installed in those nodes. Still, could you confirm that there is no oneagent pod assigned to that infrastructure node (via `oc get pods -n dynatrace -o wide`)?

That being said, I'd suggest creating a support ticket in Dynatrace, so that we can take a proper look.

Thanks,
Luis

**Comment by pahofmann** [comment] 2019-08-29 14:59
Yes there is no pod deployed for that node, we will open a support case.

**Comment by lrgar** [comment] 2019-09-05 15:03
Following up in the support case.

**Closed by lrgar** 2019-09-05 15:03 UTC

**Comment by xrow** [comment] 2020-05-26 00:27
I have the same issue. Infra nodes are not monitored. How did you solve it?

**Comment by lrgar** [comment] 2020-05-26 06:02
Hi @xrow 

There are two likely possibilities,
* Assuming also OpenShift, the cause ended up being the node selector not being set for the `dynatrace` namespace (OCP by default limits the nodes.) You can solve this problem by adding an annotation,
  ```bash
  $ oc annotate ns dynatrace --overwrite openshift.io/node-selector=""
  ```

* The infra nodes have a taint, and you need to add a toleration to OneAgent CR.

I hope this solves your problem, but if you still have issues, feel free to open an issue with Dynatrace support.

Best regards,
Luis
